---
engines:
  bundler-audit:
    enabled: true
  coffeelint:
    enabled: true
  csslint:
    enabled: true
  eslint:
    enabled: true
    channel: eslint-2
  duplication:
    enabled: true
    config:
      languages:
        - ruby
        - javascript
  rubocop:
    enabled: true
  ratings:
    enabled: true
    paths:
      - app/**
      - lib/**
      - "**.rb"
      - "**.js"
      - "**.css"
      - "**.coffee"
exclude_paths:
  - app/assets/javascripts/admin.js
  - app/assets/javascripts/app.js
  - bin/**
  - db/**
  - config/**
  - public/assets/**
  - spec/**
  - UI/**
  - vendor/**
