github_organization:    webdevtalks

development:
  github_app:           wdt-auth-dev
  github_client_id:     <%= ENV['GITHUB_CLIENT_ID'] %>
  github_client_secret: <%= ENV['GITHUB_CLIENT_SECRET'] %>

test:
  github_app:           '' # not needed for test
  github_client_id:     '' # not needed for test
  github_client_secret: '' # not needed for test

staging:
  github_app:           wdt-auth-stg
  github_client_id:     <%= ENV['GITHUB_CLIENT_ID'] %>
  github_client_secret: <%= ENV['GITHUB_CLIENT_SECRET'] %>

production:
  github_app:           wdt-auth
  github_client_id:     <%= ENV['GITHUB_CLIENT_ID'] %>
  github_client_secret: <%= ENV['GITHUB_CLIENT_SECRET'] %>
