github_organization:    webdevtalks

development: &development
  github_app:           wdt-auth-dev
  github_client_id:     <%= ENV['GITHUB_CLIENT_ID'] %>
  github_client_secret: <%= ENV['GITHUB_CLIENT_SECRET'] %>

  google_maps_api_key:  <%= ENV['GOOGLE_MAPS_API_KEY'] %>

test:
  <<: *development

staging:
  github_app:           wdt-auth-stg
  <<: *development

production:
  github_app:           wdt-auth
  <<: *development
