github_organization:    webdevtalks

development:
  github_app:           wdt-auth-dev
  github_client_id:     <%= ENV['GITHUB_CLIENT_ID'] %>
  github_client_secret: <%= ENV['GITHUB_CLIENT_SECRET'] %>

test:
  github_app:           '' # there's no need as we don't actually connect to github on testing
  github_client_id:     '' # there's no need as we don't actually connect to github on testing
  github_client_secret: '' # there's no need as we don't actually connect to github on testing

staging:
  github_app:           wdt-auth-stg
  github_client_id:     <%= ENV['GITHUB_CLIENT_ID'] %>
  github_client_secret: <%= ENV['GITHUB_CLIENT_SECRET'] %>

production:
  github_app:           wdt-auth
  github_client_id:     <%= ENV['GITHUB_CLIENT_ID'] %>
  github_client_secret: <%= ENV['GITHUB_CLIENT_SECRET'] %>
