development: &development
  github_app_name:      <%= ENV['GITHUB_APP_NAME']%>
  github_client_id:     <%= ENV['GITHUB_CLIENT_ID'] %>
  github_client_secret: <%= ENV['GITHUB_CLIENT_SECRET'] %>

  google_maps_api_key:  <%= ENV['GOOGLE_MAPS_API_KEY'] %>

production:
  <<: *development

test:
  <<: *development
